Update Испит јуни 2014

diff --git a/Испитни/Испит јуни 2014 b/Испитни/Испит јуни 2014
--- a/Испитни/Испит јуни 2014
+++ b/Испитни/Испит јуни 2014
@@ -37,14 +37,86 @@ state.slobodnašala() Кажува дека салата е слободна
 
 3.
 (40 поени) Командни процедури
-а) (15 поени) Напишете командна процедура која прима два аргументи: file1 и file2. Скриптата треба да провери дали двете датотеки имаат иста содржина. Доколку датотеките имаат иста содржина, скриптата треба да го извести корисникот за тоа и да ја избрише втората датотека. Притоа треба да го извести корисникот за тоа дали бришењето успеало или не. Доколку двете датотеки се различни по содржина, тогаш скриптата треба само да отпечати соодветна порака за корисникот.
-Скриптата треба да проверува дали корисникот ја повикал со точен број аргументи. Доколку бројот на аргументи е погрешен, потребно е да се испише упатство за користење и да заврши скриптата неуспешно. Исто така, скриптата треба да провери дали датотеките постојат. Доколку макар една од нив не постои, скриптата треба тоа да му го соопшти на корисникот и да заврши неуспешно.
+а) (15 поени) Напишете командна процедура која прима два аргументи: file1 и file2. Скриптата треба да провери дали двете датотеки имаат иста содржина. Доколку датотеките имаат иста содржина, скриптата треба да го извести 
+корисникот за тоа и да ја избрише втората датотека. Притоа треба да го извести корисникот за тоа дали бришењето успеало или не. Доколку двете датотеки се различни по содржина, тогаш скриптата треба само да отпечати
+соодветна порака за корисникот.
+Скриптата треба да проверува дали корисникот ја повикал со точен број аргументи. Доколку бројот на аргументи е погрешен, потребно е да се испише упатство за користење и да заврши скриптата неуспешно. Исто така, скриптата 
+треба да провери дали датотеките постојат. Доколку макар една од нив не постои, скриптата треба тоа да му го соопшти на корисникот и да заврши неуспешно.
 Скриптата зачувајте ја во домашниот именик, под име zada-t1.sh.
 Пример за користење на скриптата: zad3a-ti sh myfiles/a.txt b.txt
+
 6) (25 поени) Напишете командна процедура која на дадена локација (прв аргумент на скриптата) ќе ги пронајде сите shell
-командни процедури и ќе провери дали корисникот има привилегии за нивно извршување (ќе се отпечатат соодветни пораки за секоја од скриптите. Доколку корисникот нема привилегии за извршување на пронајдената скрипта, вашата скрипта треба да ги додаде овие привилегии и да го извести корисникот за успешноста на промената.
+командни процедури и ќе провери дали корисникот има привилегии за нивно извршување (ќе се отпечатат соодветни пораки за секоја од скриптите. Доколку корисникот нема привилегии за извршување на пронајдената скрипта, 
+вашата скрипта треба да ги додаде овие привилегии и да го извести корисникот за успешноста на промената.
 Напомена: Наставката не секогаш е доволен индикатор за содржината на датотеката или именикот. Проверете ги датотеките дали содржат некоја карактеристика во својата содржина која би ги идентификувала како командни процедури.
-Скриптата треба да проверува дали корисникот ја повикал со точен број аргументи. Доколку бројот на аргументи е погрешен. потребно е да се испише упатство за користење и да заврши скриптата неуспешно. Исто така, скриптата треба да провери дали локацијата наведена како пре аргумент постои и доколку не треба да го извести корисникот и да заврши неуспешно.
+Скриптата треба да проверува дали корисникот ја повикал со точен број аргументи. Доколку бројот на аргументи е погрешен. потребно е да се испише упатство за користење и да заврши скриптата неуспешно. Исто така, скриптата 
+треба да провери дали локацијата наведена како пре аргумент постои и доколку не треба да го извести корисникот и да заврши неуспешно.
 Скриптата зачувајте ја во домашниот именик, под име 6-13..
 Пример за користење на скриптата: 30-11.th/os-files
 Your solution file
+
+а)
+#!/bin/bash
+
+if [ $# -ne 2 ];then
+echo "USAGE: file1 file2"
+exit 1
+
+file1=$1
+file2=$2
+
+if [ ! -f "$file1" ];then
+echo "file1 doesn't exist!"
+exit 1
+fi
+
+if [ ! -f "$file2" ];then
+echo "file2 doesn't exist!"
+exit 1
+fi
+
+if cmp -q "$file1" "$file2";then
+echo "file1 and file2 are same!"
+rm "$file2"
+if [ $? -eq 0 ];then
+echo "file2 was successfully removed."
+else
+echo "file2 was not successfully removed."
+fi
+else
+echo "file1 and file2 are diffrent."
+fi
+
+6)
+
+if [ $# -ne 1 ];then
+echo "USAGE: <directory-path>"
+exit 1
+fi
+
+directory=$1
+if [ ! -d "$directory" ];then
+echo "Error: Directory '$directory' does not exist."
+exit 1
+fi
+
+for file in "$directory"/*;do
+
+if [ ! -f "$file" ];then
+continue
+fi
+
+if head -n 1 "$file" | grep -q "^#!.*sh";then
+if [ -x "$file" ];then
+echo "User has execute premissions"
+else
+chmod +x "$file"
+if [ #? -eq 0 ];then
+echo "Execute permissions added succesfully"
+else
+echo "Failed to add execute permissions"
+fi
+fi
+fi
+done
+exit 0
