Update Испит јуни 2015

diff --git a/Испитни/Испит јуни 2015 b/Испитни/Испит јуни 2015
--- a/Испитни/Испит јуни 2015
+++ b/Испитни/Испит јуни 2015
@@ -2,15 +2,69 @@
 ТЕРМИН 1
 1.
 UNIX команди
-а) (5 поени) Напишете UNIX команда со која ќе ги прикажете сите детали за најавувањата на корисници кои се случиле во текот на вчерашниот ден среда, 17 јуни. Командата снимете ја во датотека за3а-11.sh., во вашиот домашен именик на н серверот.
-6) (10 поени) Напишете UNIX команда со која ќе ги прикажете корисничките имиња на корисниците кои имаат тековно активни процеси, стартувани во тек на 10:00 часот (10:00-10:59), листата да биде нумерички сортирана и да не содржи дупликати Командата снимете ја во датотека zаd3b-11.ch, во вашиот домашен именик на os finki skin серверот.
+а) (5 поени) Напишете UNIX команда со која ќе ги прикажете сите детали за најавувањата на корисници кои се случиле во текот на вчерашниот ден среда, 17 јуни. Командата снимете ја во датотека за3а-11.sh., во вашиот 
+домашен именик на н серверот.
+6) (10 поени) Напишете UNIX команда со која ќе ги прикажете корисничките имиња на корисниците кои имаат тековно активни процеси, стартувани во тек на 10:00 часот (10:00-10:59), листата да биде нумерички сортирана и 
+да не содржи дупликати Командата снимете ја во датотека zаd3b-11.ch, во вашиот домашен именик на os finki skin серверот.
 Your solution file
+а)nano ~/za3a-11.sh
+chmod +x ~/za3a-11.sh 
+last|grep "Wed Jun 17"
+6) nano ~/za3b-11.sh
+chmod +x ~/za3b-11.sh 
+ps -eo user,lstart| grep "10:"|awk '{print $1}'|sort|uniq
+
 2.
 UNIX командна процедура
-(25 поени) Да се напише командна процедура која во даден именик (пря аргумент) и сите негови подименици рекурзивно кети пронајде сите датотеки модифицирани на даден датум (итор аргумент). За секоја од пронајдените датотеки треба да се провери дали во содржината има структура за повторување и истата да се искоментира. Да се зачуваат овие измени во самата датотека
+(25 поени) Да се напише командна процедура која во даден именик (прв аргумент) и сите негови подименици рекурзивно кети пронајде сите датотеки модифицирани на даден датум (втор аргумент). За секоја од пронајдените 
+датотеки треба да се провери дали во содржината има структура за повторување и истата да се искоментира. Да се зачуваат овие измени во самата датотека
 Направете проверка дали се проследени потребните аргументи и доколку не се, прикажете соодветно упатство за употреба. Доколку изворниот именик не постои, скриптата треба да го извести корисникот за тоа и да заврши неуспешно. Да се внимава вториот аргумент на скриптата да биде во форматот кој што се користи за датум при детално листање на именици (на пример: Jun 18).
 Командната процедура снимете ја под името zad4-11.sh. во вашиот домашен именик на os. Fink серверот.
 Your solution file
+#!/bin/bash
+if [ $# -ne 2 ];then
+echo "USAGE: directory date"
+exit 1
+fi
+
+DIRECTORY=$1
+MOD_DATE=$2
+
+if [ ! -d "$DIRECTORY" ]; then
+    echo "Error: Directory '$DIRECTORY' does not exist."
+    exit 1
+fi
+
+FILES=$(find "$DIRECTORY" -type f -newermt "$MOD_DATE 00:00:00" ! -newermt "$MOD_DATE 23:59:59")
+
+if [ -z "$FILES" ]; then
+    echo "No files found modified on $MOD_DATE."
+    exit 0
+fi
+
+comment_repeating_lines() {
+    local file=$1
+    awk '
+    {
+        count[$0]++
+        if (count[$0] > 1) {
+            print "# " $0
+        } else {
+            print $0
+        }
+    }' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
+}
+
+for file in $FILES; do
+    echo "Processing: $file"
+    comment_repeating_lines "$file"
+done
+
+echo "Processing complete."
+
+exit 0
+
+
 3.
 Java I/O
 (30 поени) Напишете ги следните методи кои работат со бинарната датотека apt. dat. Оваа датотека содржи типови на податоци со фиксна големина од 2 бајти. Се претпоставува дека датотеката може да биде многу голема (мерена во гигабајти). Влез/излез операциите да се имплементираат со помош на Stream-ови.
