Update Испит јуни 2024

diff --git a/Испитни/Испит јуни 2024 b/Испитни/Испит јуни 2024
--- a/Испитни/Испит јуни 2024
+++ b/Испитни/Испит јуни 2024
@@ -65,6 +65,43 @@ DEBUG: 1
 INFO: 2
 WARN: 6
 ERROR: 3
+#!/bin/bash
+
+if [ $# -ne 2 ];then
+echo "Usage: script.sh <STATUS> <MONTH>"
+exit 1
+fi
+
+status=$1
+mesec=$2
+
+if ! [["$mesec" =~ ^[0-9]{4}-(0[0-9]|1[0-2])$ ]]; then
+echo "Invalid month format. Correct format: YYYY-MM"
+exit 1
+fi
+
+while read -r line; do
+log_date=$(echo "$line"|awk '{ print $1}')
+log_status=$(echo "$line"|akw '{print $3}')
+if [[ "$log_date" -eq "$mesec"* && "$log_status" -eq "$status" ]];then
+log_count=$((log_count+1))
+fi
+done <log_file.txt
+echo "Number of logs with status '$status' in month '$mesec': $LOG_COUNT"
+
+#ili moze vaka
+
+log_count=$(cat test|grep "$status"|grep "$mesec"|wc -l)
+
+
+ip=$(cat test| grep "$status"|awk '{print $NF}'|uniq -c | awk '{print $2}' )
+
+echo "Most common IP address for logs with status '$status': $IP"
+
+for i in DEBUG INFO WARN ERROR;do
+counter=$(grep "$i" test| grep "$mesec|wc -l)
+echo "$i:$counter"
+done
 
 Задача 3 - СИНХРОНИЗАЦИЈА
 Потребно е да се направи имлементација на серверскиот дел на мрежната апликација „Last word“ која ќе го имплементира следното сценарио:
